name: Test Manual Yes No Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "GitHub Event: ${{ toJson(github.event) }}"
          echo "Hello ${{ github.event.inputs.name }}"
